### ISSUE TITLE
V1 Roadmap

### ISSUE THREAD

**Issue by DanielS-source** [Diego-a-lopez/ScapeTheAds#14]
- [x] (Unity) Modo infinito vs modo nivel
- [x] (Unity) Funcionalidad de saltar de nivel en nivel
- [x] (Unity) Sistema de cuenta atras y puntuación
- [x] (Unity) Añadir 2 niveles
- [x] (Unity) Assests para los niveles
- [x] (Unity/Android) Lanzar pantallas victoria o derrota según el resultado de Unity
- [x] (Android) Settings
- [x] (Android) Mejoras UI/UX
- [x] (Android) Cerrar sesión
- [x] (Documentación) Repasar todo. Actualizar mockups figma, organización, etc
- [x] (Documentación) Necesidades sensórica
- [x] (Documentación) Lean canvas
